//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserContact
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public string PhoneNumber { get; set; }
        public string City { get; set; }
        public string Distirct { get; set; }
        public string Address { get; set; }
        public bool IsActive { get; set; }
        public bool IsDefaultAddress { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool Deleted { get; set; }
    
        public virtual User User { get; set; }
    }
}
